### ISSUE TITLE
sixth US Setings

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#1]
## Value Proposition

**As a** user
**I want to** see my stored settings in "sound
**so that** i can recreate the sound" 
​

## Description
![Capstone_scetch_7](https://github.com/JonasDaJones/capstone-project/assets/126177200/383cf041-3784-48de-9746-2a21fc00c3e2)

## Acceptance Criteria

- [ ] on "sound" there is a list called stored settings with the stored settings
      ​

## Tasks

- [ ] create branch stored settings
- [ ] create component stored settings
- [ ] receive data from form "settings"
- [ ] render data in list
      ​

**Comment by JonasDaJones** [comment]
this issue is the same as the last one
