### ISSUE TITLE
US8 only show existant values

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#11]
## Value Proposition

**As a** user
**I want to** see only values on my spec - sheet, that are existant
**so that** i will be able to capture information faster without disturbance by empty data fields.
​

## Description

except in tables, only fields with values should be shown. (In tables, there are fields with no data, but it could be added (own measurement). In other cases, there are no values because there is no key (A Pedal with 3 Knobs cannot have a value for Knob 4).

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/46f61810-11bc-4149-aba4-102a3cc72699)

​

## Acceptance Criteria

- [ ] PedalSpecs and PedalSound have a (rough) styling (placement, tables)
- [ ] All fields shown have a value.
- [ ] Tables might show empty fields.
      ​

## Tasks

- [ ] create branch "tidy-details"
- [ ] in PedalDetailContent: filter Data before rendering
- [ ] create pedal-details-specs.styled.js
- [ ] style PedalSpecs
- [ ] create pedal-details-sound.styled.js
- [ ] style PedalSound
      ​

**Comment by JonasDaJones** [comment]
renamed from US7 to US8, as US7 ("seventh US") already exists.
