### ISSUE TITLE
US9 New Pedal

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#12]
## Value Proposition

**As a** user
**I want to** add new pedals to my collection
**so that** i have an overview of what i have
​

## Description

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/263caf60-8fac-48f0-b9e4-19d1e5fb42a3)

...
​

## Acceptance Criteria

- [ ] on my pedal Gallery there is a add new pedal button
- [ ] by pressing the button i get to first form page
- [ ] page contains inputs for name, manufacturer, category, origin, width, depth and height,
- [ ] page contains radio-button for mono/ stereo
- [ ] page contains input field for tags
- [ ] I can cancel my input and reset the form without saving

      ​

## Tasks

- [x] create new branch "pedal-form-first"
- [x] create component "new-pedal-main"
- [ ] create form (local Storage)
- [ ] create input fields for name, manufacturer, category, origin, width, depth and height, tags, mono/ stereo
- [ ] create (insert) a random id generator
      ​

**Comment by marcbendixen** [comment]
Hey 👋 
good job!
I only have one little thing regarding this _"I can interrupt the input and resume later"_.
This sounds like "editing functionality" to me, and could be a whole user story in itself. Just keep that in mind.

**Comment by JonasDaJones** [comment]
thanks. I deleted that for now and will have a look at that feature later.
