### ISSUE TITLE
US10 New Pedal

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#15]
## Value Proposition

**As a** user
**I want to** upload an image of my pedal
**so that** i can show off to my friends
​

## Description

...

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/0b570dbe-9a6e-427a-840e-b4f1f9b810d6)

​

## Acceptance Criteria

- [ ] on my form there is a button for image upload
- [ ] as i click the button i get a field "choose image"
- [ ] after uploading it is visible on my pedal detail main page
      ​

## Tasks

- [ ]  Create new branch upload image
- [ ] create choose image button and function
- [ ] implement cloudinary

      ​

**Comment by Danielschuetzle** [comment]
LGTM 👍🏻
