### ISSUE TITLE
US11 New Pedal

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#16]
## Value Proposition

**As a** user
**I want to** add specs to my new pedal data
**so that** i can refer to them when i need them
​

## Description

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/3ab028be-6de3-419f-9a86-9ede9443c3a0)

...
​

## Acceptance Criteria

- [ ] There are input fields i can fill
- [ ] There are dropdown menus for data that expect discrete answers
- [ ] There is a back button 
      ​

## Tasks

- [ ] create branch "pedal-form-specs"
- [ ] create component
- [ ] create dropdown fields for bypass (true/ buffered/ selectable), voltage (9V, 12V, 18V, 24V, other), polarity (center begative/ center positive),
- [ ] create radio - button for battery (yes/ no)
- [ ] create input fields for impedance and current draw
- [ ] provide the input fields with corresponding functionality 
- [ ] insert back-button

      ​
