### ISSUE TITLE
US12 New Pedal

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#17]
## Value Proposition

**As a** user
**I want to** add further description to the pedal details card
**so that** i know about switches and knobs as well as about jack - placement.
​

## Description

Information: As the "next" button would be without function, as there still is no next page, this is on the scribble only.
...

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/ec4998f2-96fb-4f6b-b506-1ce9996eb77a)

​

## Acceptance Criteria

- [ ] There is a form with inputs for footswitches,  knobs, switches, dipswitches, jacks on the left, the right, the top and the front.
- [ ] there is a back button that brings me to the previous section of the form
- [ ] I can save my inputs and exit, cancel my input an clear the form. 
      ​

## Tasks

- [ ] create inputs for  footswitches,  knobs, switches, dipswitches, jacks on the left, the right, the top and the front.
- [ ] add submit button with corresponding function
- [ ] add cancel button with corresponding function
- [ ] add session storage function to the back button

      ​

**Comment by dimitriosxmi** [comment]
LGTM!
