### ISSUE TITLE
US13 New Pedal

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#18]
## Value Proposition

**As a** user
**I want to** be able to add some personal comments to my pedal details

**so that** i later can decide, which pedal to select
​

## Description

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/1caf0d22-b352-4fb4-a8d9-0fbe8da6851c)

...
​

## Acceptance Criteria

- [ ] There are textfields for "nice to know", "sound description" and "my comment"
- [ ] There is a back button top right of the page
- [ ] at the upper right corner there is schown, in which section of the form i am (4/4)
- [ ] there is a cancel button that cleard my form
- [ ] there is a save button that submits my form
      ​

## Tasks

- [ ] create branch "personal-notes"
- [ ] create component
- [ ] create input textfields with corresponding labels
- [ ] create buttons with corresponding functions (data should be stored in local storage for now)
      ​

**Comment by dimitriosxmi** [comment]
## LGTM! Nice US
Notes:
- In your acceptance criteria the 2nd point should say `top left of` instead of `top right of`
- Given your cancel button is supposed to just clear the form (as you stated in your acceptance criteria at the 4th point) I believe to rename it to `reset` or maybe `clear` would be more fit
