### ISSUE TITLE
US14 New Pedal

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#19]
## Value Proposition

**As a** user
**I want to** have direct access to the manufacturers manual out of the app
**so that** i can find more detailed information when i need it
​

## Description

![Image](https://github.com/JonasDaJones/capstone-project/assets/126177200/9522ea28-118f-4428-9ec9-edb1c4e73247)

...
​

## Acceptance Criteria

- [ ] There is an input field where a link can be placed
      ​

## Tasks

- [ ] create input link
- [ ] decide where to place the link in the app
      ​

**Comment by dimitriosxmi** [comment]
## LGTM! straightforward and simple!
