### ISSUE TITLE
first US

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#2]
## Value Proposition

**As a** user
**I want to** view a detailed list of my fx pedals
**so that** i have an overview of what i have
​

## Description

![image](https://github.com/JonasDaJones/JonasDaJones/assets/126177200/753ce606-b7ee-4e7f-9d56-b0c99190cc74)

​

## Acceptance Criteria

- [ ] Header is always visible
- [ ] all data for one pedal is shown in one card
- [ ] cards can be scrolled horizontally
- [ ] content of the card can be scrolled vertically
      ​

## Tasks

- [ ] create branch pedal galery
- [ ] create list of pedals
- [ ] create data
- [ ] create galery
      ​
