### ISSUE TITLE
second US Form

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#3]
## Value Proposition

**As a** user
**I want to**  view the main data and a hint to more data in TABs
**so that** so that I can find the relevant information more quickly (and so that I can use the first page to show off to my friends).
​

## Description

![Image](https://github.com/JonasDaJones/JonasDaJones/assets/126177200/39df175c-cb90-4245-8231-17b6f485d6cb)

...
​

## Acceptance Criteria

- [ ] Only visible items in Card: Name, manufacturer, category, tags
- [ ] TAB at the top of the card: main,
- [ ] TAB for main is "active" (same color as card)

      ​

## Tasks

- [ ] create branch "first card-page"
- [ ] create styled components
- [ ] create TAB Buttons
- [ ] make classes
- [ ] make classes visible if TAB (Button) of main is active
      ​
