### ISSUE TITLE
third US Form

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#4]
## Value Proposition

**As a** user
**I want to** click tabs besides the main
**so that** i get access to further information
​

## Description

...

![Image](https://github.com/JonasDaJones/JonasDaJones/assets/126177200/1148bd1d-ce7a-40ae-8e63-a482ef9b7414)

​

## Acceptance Criteria

- [ ] by tapping on tabs "specs" or "sound" data according to this criteria is shown
- [ ] data not according to active tab is not visible
- [ ] active tab has same color as card
- [ ] non active tabs are grey
      ​

## Tasks

- [ ] create new branch "detailed data"
- [ ] create two more buttons "specs" and "sound"
- [ ] change visibility of data according to active tab
- [ ] 
      ​
