### ISSUE TITLE
fourth US Form

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#5]
## Value Proposition

**As a** user
**I want to** take notes of my favorite settings
**so that** i can store them and recall them later in a "stored settings" list
​

## Description

...
​

![Image](https://github.com/JonasDaJones/JonasDaJones/assets/126177200/e88fb00d-fcbc-4c47-b29d-b9e37dca322b)

## Acceptance Criteria

- [ ] tab on a Button called "Settings" deactivates the former Button
- [ ] tab on Button Settings shows a table with the available knobs and switches in one column
- [ ] in a second column there are input - fields to write setting values
- [ ] under the table there is a input called "Settings Name"
- [ ] and a "SAVE" Button
      ​

## Tasks

- [ ] create new branch "settings form"
- [ ] create Button "Settings"
- [ ] add visibility rules when button is active
- [ ] create form component
      ​
