### ISSUE TITLE
seventh US Settings

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/capstone-project#7]
## Value Proposition

**As a** user
**I want to** manipulate the settings by turning knobs and clicking switches instead of entering values by typing
**so that** i do not have to translate the knob setting i see on my pedal to values i enter.
​

## Description

![Capstone_scetch_6(1)](https://github.com/JonasDaJones/capstone-project/assets/126177200/990fbbaf-3d7d-4390-9fcc-e506cc0ec566)

​

## Acceptance Criteria

- [ ] buttons to turn
- [ ] switch to flip
- [ ] enter name input  
- [ ] save button
      ​

## Tasks

- [ ] create branch buttons and knobs
- [ ] create buttons and knobs
- [ ] write test
- [ ] make  buttons and knobs functional
      ​
